from typing import List
from ..utils.findings import Finding
import html

CSS = """
:root{ --bg:#0b0d10; --card:#13161a; --text:#eef1f5; --muted:#a7b0bf; --hi:#ff7272; --md:#ffb84d; --lo:#7ed957; }
*{ box-sizing:border-box; }
body{ margin:32px; padding:0; background:var(--bg); color:var(--text); font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,'Helvetica Neue',Arial,'Noto Sans',sans-serif; line-height:1.5; }
h1{ font-size:1.8rem; margin:0 0 16px 0; }
.summary{ color:var(--muted); margin-bottom:24px; }
.table{ width:100%; border-collapse:separate; border-spacing:0; background:var(--card); border-radius:16px; overflow:hidden; }
thead th{ text-align:left; font-weight:600; padding:14px 16px; border-bottom:1px solid rgba(255,255,255,.08); }
tbody td{ vertical-align:top; padding:14px 16px; border-top:1px solid rgba(255,255,255,.05); }
tbody tr:first-child td{ border-top:none; }
.sev{ font-weight:700; }
.badge{ display:inline-block; padding:.15rem .5rem; border-radius:999px; font-size:.8rem; }
.badge.CRITICAL{ background:var(--hi); color:#1a1a1a; }
.badge.HIGH{ background:#ff8a65; color:#1a1a1a; }
.badge.MEDIUM{ background:var(--md); color:#1a1a1a; }
.badge.LOW{ background:#61c0ff; color:#1a1a1a; }
.badge.INFO{ background:#bdbdbd; color:#1a1a1a; }
.meta{ color:var(--muted); font-size:.9rem; margin-top:6px; }
.footer{ color:var(--muted); margin-top:24px; font-size:.85rem; }
"""

def _sev_badge(sev: str) -> str:
    s = (sev or "info").upper()
    return f"<span class='badge {html.escape(s)}'>{html.escape(s)}</span>"

def emit(findings: List[Finding], title: str = "kuberoast2 report") -> str:
    rows = []
    for f in findings:
        rows.append(
            "<tr>"
            f"<td class=\"sev\">{_sev_badge(f.severity)}</td>"
            f"<td><div>{html.escape(f.title or '')}</div><div class=\"meta\">{html.escape(f.category or '')}</div></td>"
            f"<td>{html.escape(f.resource or '-')}</td>"
            f"<td><div>{html.escape(f.description or '')}</div>"
            + (f"<div class=\"meta\">Remediation: {html.escape(f.remediation or '')}</div>" if f.remediation else "")
            + "</td>"
            "</tr>"
        )

    body = (
        "<!doctype html><html lang=\"en\">"
        "<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        f"<title>{html.escape(title)}</title><style>{CSS}</style></head>"
        "<body>"
        f"<h1>{html.escape(title)}</h1>"
        f"<div class=\"summary\">Findings: {len(findings)}</div>"
        "<table class=\"table\"><thead><tr>"
        "<th>Severity</th><th>Title</th><th>Resource</th><th>Description</th>"
        "</tr></thead><tbody>"
        + "".join(rows) +
        "</tbody></table><div class=\"footer\">Generated by kuberoast2</div>"
        "</body></html>"
    )
    return body
